apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-dep
  template:
    metadata:
      labels:
        app: todoapp-dep
    spec:
      containers:
        - name: todoapp
          image: todo_app:latest
          imagePullPolicy: IfNotPresent